name: Build and Publish (Non-Release)

on:
  pull_request:
    branches:
      - master
      - main
  push:
    branches:
      - master
      - main

jobs:
  ci-draft:
    uses: ./.github/workflows/ci-build-publish.yml
    secrets: inherit
    with:
      environment: dev
      is_publish: ${{ github.event_name == 'push' }}
      trigger_docker: ${{ github.event_name == 'push' }}
      trigger_deploy: ${{ github.event_name == 'push' }}
      pacticipant: CPRefDataCourtHouseProvider
      pact_env: dev/pactTest
